:technologist: 🛡️ Improve stability of Ledger Nodes (#1356)
Sometimes, after a spot reclaim event, 3/4 of the Ledger Nodes will
successfully recover, however, 1/4 of them will be stuck in a recovering
state.
Added a TCP port check to the liveness probe to restart the pod if it
gets stuck in a recovering state.

* :technologist: Lighter Ledger Browser probes
  * `/status/text` is quite a lot of data that's not necessary (±25KB)
  * `/status` is ±320B
  * Set `terminationGracePeriodSeconds` to `10` for more aggressive
termination of Ledger Browser

diff --git a/helm/ledger-nodes/values.yaml b/helm/ledger-nodes/values.yaml
--- a/helm/ledger-nodes/values.yaml
+++ b/helm/ledger-nodes/values.yaml
@@ -78,6 +78,10 @@ livenessProbe:
       if ! grep -q '"Has_write_consensus": true' "$INFO_FILE"; then
         echo "Error: No write consensus"
         exit 1
+      fi &&
+      if ! (timeout 1 bash -c "</dev/tcp/localhost/9701" 2>/dev/null); then
+        echo "Error: Port 9701 is not open"
+        exit 1
       fi
   initialDelaySeconds: 60
   periodSeconds: 10
